name: Release Alpine Packages

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu for building Alpine packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version of checkout

      - name: Set up environment
        run: |
          echo "Setting up environment"
          echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV  # Set the target architecture

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create Alpine package
        run: |
          chmod +x ./package_alpine.sh
          ./package_alpine.sh ${{ steps.vars.outputs.tag }}  # Pass the version tag to the packaging script

      - name: Rename binaries
        run: |
          echo "Renaming binaries to include architecture"
          mv ./build/${PACKAGE_NAME}/your_binary ./build/${PACKAGE_NAME}/your_binary-${TARGET_ARCH}  # Adjust the path and name

      - name: Verify file existence
        run: |
          ls -la ./build/${PACKAGE_NAME}/  # List files to verify output

      - name: Upload files to a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/${PACKAGE_NAME}/your_binary-${TARGET_ARCH}  # Upload renamed binaries
            ./build/${PACKAGE_NAME}/*.apk  # Adjust this path to include generated APK files
