name: Release Alpine Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: alpine:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: baking-bad/stone-prover
          token: ${{ secrets.GITHUB_TOKEN }}
          path: stone-prover

      - name: Checkout packaging code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "Setting up environment"
          echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
        
      - name: Test
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Make package_alpine.sh executable
        run: chmod +x ./package_alpine.sh

      - name: Create Alpine package
        run: |
          ./package_alpine.sh ${tag}
          env:
            TARGET_ARCH: x86_64
            tag: ${steps.vars.outputs.tag}

      - name: Rename binaries
        run: |
          echo "Renaming binaries to include architecture"
          mv ./build/${{ steps.vars.outputs.tag }}/cpu_air_prover ./build/${{ steps.vars.outputs.tag }}/cpu_air_prover-${TARGET_ARCH}
          mv ./build/${{ steps.vars.outputs.tag }}/cpu_air_verifier ./build/${{ steps.vars.outputs.tag }}/cpu_air_verifier-${TARGET_ARCH}

      - name: Verify file existence
        run: |
          ls -la ./build/${{ steps.vars.outputs.tag }}/ 

      - name: Upload files to a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/${{ steps.vars.outputs.tag }}/cpu_air_prover-${TARGET_ARCH}
            ./build/${{ steps.vars.outputs.tag }}/cpu_air_verifier-${TARGET_ARCH}
            ./build/${{ steps.vars.outputs.tag }}/*.apk