name: Release

on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Build and push Alpine package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.tag }}
        run: |
          docker build -t prover:latest .
          docker tag prover:latest prover:${TAG}
          docker push prover:${TAG}

      - name: Create Alpine package
        env:
          TAG: ${{ github.event.tag }}
        run: |
          docker run --rm -v ${PWD}:/app prover:${TAG} /bin/sh -c "apk add --no-cache --virtual .build-deps alpine-sdk && mv /app/prover /app/prover-${TAG} && tar -czf prover-${TAG}.tar.gz prover-${TAG} && mv prover-${TAG}.tar.gz /app/"

      - name: Upload Alpine package
        uses: actions/upload-artifact@v2
        with:
          name: prover-${TAG}.tar.gz
          path: prover-${TAG}.tar.gz