name: Release Alpine Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: alpine:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          echo "Configuring environment variables"
          echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV
          echo "BUILD_ENVIRONMENT=production" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +"%H:%M:%S")" >> $GITHUB_ENV
        env:
          TARGET_ARCH: x86_64
          BUILD_ENVIRONMENT: production

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          TARGET_ARCH: ${{ env.TARGET_ARCH }}
          BUILD_ENVIRONMENT: ${{ env.BUILD_ENVIRONMENT }}

      - name: Test
        run: |
          echo "Running tests for ${TARGET_ARCH} architecture"
          chmod +x ./test.sh
          ./test.sh
        env:
          TARGET_ARCH: ${{ env.TARGET_ARCH }}
          BUILD_ENVIRONMENT: ${{ env.BUILD_ENVIRONMENT }}

      - name: Make package_alpine.sh executable
        run: chmod +x ./package_alpine.sh

      - name: Create Alpine package
        run: |
          echo "Creating Alpine package for ${TARGET_ARCH} architecture"
          ./package_alpine.sh ${{ steps.vars.outputs.tag }}
        env:
          TARGET_ARCH: ${{ env.TARGET_ARCH }}

      - name: Rename binaries
        run: |
          echo "Renaming binaries to include architecture"
          mv ./build/${{ steps.vars.outputs.tag }}/cpu_air_prover ./build/${{ steps.vars.outputs.tag }}/cpu_air_prover-${{ env.TARGET_ARCH }}
          mv ./build/${{ steps.vars.outputs.tag }}/cpu_air_verifier ./build/${{ steps.vars.outputs.tag }}/cpu_air_verifier-${{ env.TARGET_ARCH }}

      - name: Verify file existence
        run: |
          ls -la ./build/${{ steps.vars.outputs.tag }}/

      - name: Upload files to a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/${{ steps.vars.outputs.tag }}/cpu_air_prover-${{ env.TARGET_ARCH }}
            ./build/${{ steps.vars.outputs.tag }}/cpu_air_verifier-${{ env.TARGET_ARCH }}
            ./build/${{ steps.vars.outputs.tag }}/*.apk
