name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: alpine:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV
        echo "BUILD_ENVIRONMENT=production" >> $GITHUB_ENV

    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh
    
    - name: Test
      run: |
        chmod +x ./test.sh
        ./test.sh

    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Make package script executable
      run: |
        chmod +x ./package_alpine.sh
        ./package_deb.sh ${{ steps.vars.outputs.tag }}

    - name: Rename binaries 
      run: |
        echo "Renaming binaries to include architecture"
          mv /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_prover ./cpu_air_prover-${TARGET_ARCH}
          mv /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_verifier ./cpu_air_verifier-${TARGET_ARCH}

   
    - name: Verify file existence
      run: |
        ls -la ./
        ls -la /tmp/stone-prover/

    - name: Upload files to a GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./cpu_air_prover-${TARGET_ARCH}
          ./cpu_air_verifier-${TARGET_ARCH}
        tag_name: ${{ steps.vars.outputs.tag }}

