name: Release Alpine Packages
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV
          echo "BUILD_ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Build prover
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Run tests
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Set output for tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Alpine package
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -w /work alpine:latest /bin/sh -c "
            apk add --no-cache alpine-sdk
            adduser -D builder
            addgroup builder abuild
            echo 'builder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
            su builder -c '
              abuild-keygen -a -n
              chmod +x ./package_alpine.sh
              ./package_alpine.sh ${{ steps.vars.outputs.tag }}
            '
          "

      - name: Move APK to workspace
        run: |
          sudo mv /home/builder/packages/work/*/*.apk .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.apk
          tag_name: ${{ steps.vars.outputs.tag }}