name: Release Alpine Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Alpine build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y apk-tools build-essential

      - name: Build Alpine Package
        run: |
          ./package_alpine.sh

      - name: Upload Alpine Package
        uses: actions/upload-artifact@v3
        with:
          name: alpine-package
          path: ./build/output/*.apk
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/output/*.apk
