name: Release Alpine Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV
          echo "BUILD_ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Build prover
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Run tests
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Set output for tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Make package script executable
        run: |
          chmod +x ./package_alpine.sh

      - name: Package Alpine
        run: |
          ./package_alpine.sh ${{ steps.vars.outputs.tag }}

      - name: Rename binaries
        run: |
          echo "Renaming binaries to include architecture"
          mv /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_prover ./cpu_air_prover-${TARGET_ARCH}
          mv /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_verifier ./cpu_air_verifier-${TARGET_ARCH}

      - name: Verify file existence
        run: |
          ls -la ./
          ls -la /tmp/stone-prover/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./cpu_air_prover-${TARGET_ARCH}
            ./cpu_air_verifier-${TARGET_ARCH}
          tag_name: ${{ steps.vars.outputs.tag }}
